services:
  - type: web
    name: student-management-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production